import { Inter,Marcellus,Crimson_Text,Kanit } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/components/state";
import {NextUIProvider} from "@nextui-org/react";
const inter = Inter({ subsets: ["latin"] });
const marcellus=Marcellus({subsets:["latin"],weight:["400"],variable:"--font-marcellus"})
const crimson=Crimson_Text({subsets:["latin"],weight:["400","600","700"],variable:"--font-crimson"})
const kanit=Kanit({subsets:["latin"],weight:["400","800","900","700","600","500"],variable:"--font-kanit"})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={`${inter.className} ${marcellus.variable} ${crimson.variable} ${kanit.variable}`}>
      <NextUIProvider>
      <AuthContextProvider>{children}</AuthContextProvider>
      </NextUIProvider></body>
    </html>
    
  );
}
